# Generated by Django 3.0.2 on 2020-01-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('day', models.CharField(max_length=10)),
                ('wcd', models.CharField(max_length=100)),
                ('ko_sky', models.CharField(max_length=100)),
            ],
        ),
    ]
