# Generated by Django 3.0.1 on 2019-12-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
